### ISSUE TITLE
part 3 tutorial getting: key :time_zone not found in: %{name: "Bigardone"}

### ISSUE THREAD

**Issue by CharlesIrvineKC** [bigardone/calendlex#4]
Hi,

I'm walking through part 4 our your LiveView tutorial. When I edit init_assigns.ex as shown in the screen shot below I get the error shown in the second screen shot. I'm pretty new to Phoenix and LiveView, so I'm not able to determine the cause of the problem. Can you guess what my problem might be?

Thanks

![Screen Shot 2022-06-20 at 8 48 24 AM](https://user-images.githubusercontent.com/657002/174616509-8ccd3e7a-339b-4a36-869c-1200d60e237f.png)

![Screen Shot 2022-06-20 at 8 51 33 AM](https://user-images.githubusercontent.com/657002/174616638-9c2e0c1c-e48c-43d0-8d8c-db1d50a906fc.png)

**Comment by CharlesIrvineKC** [comment]
I just happened to notice that someone else had the same problem:
https://elixirforum.com/t/unexpected-behavior-with-operator-with-get-connect-params-socket/46581

So, it seems that there is a problem with the tutorial.

**Comment by darethas** [comment]
Simply add the key yourself to the owner map in `config.exs`
